spring.application.name=spring-reservas-api

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Caché
spring.cache.type=simple

# Actuator
management.endpoints.web.exposure.include=health,info,metrics

jwt.secret=${JWT_SECRET:EstaEsUnaClaveSuperSecretaYMuyLargaDeMasDe32CaracteresParaHS256!}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.prefix=${JWT_PREFIX:Bearer}
jwt.header=${JWT_HEADER:Authorization}

logging.level.org.springframework.security=DEBUG
