spring.application.name=spring-reservas-api

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Caché
spring.cache.type=simple

# Actuator
management.endpoints.web.exposure.include=health,info,metrics

jwt.secret=${JWT_SECRET:EstaEsUnaClaveSuperSecretaYMuyLargaDeMasDe32CaracteresParaHS256!}
jwt.expiration=${JWT_EXPIRATION:43200000}
jwt.prefix=${JWT_PREFIX:Bearer}
jwt.header=${JWT_HEADER:Authorization}

# ===================================================================
# CONFIGURACIÓN DE RESILIENCE4J (CIRCUIT BREAKER)
# ===================================================================

resilience4j.circuitbreaker.instances.pagoCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.pagoCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.pagoCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.pagoCircuitBreaker.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.instances.pagoCircuitBreaker.permitted-number-of-calls-in-half-open-state=3


# ===================================================================
# CONFIGURACIÓN DE ACTUATOR PARA MONITOREAR EL CIRCUITO
# ===================================================================
# Habilita los indicadores de salud del Circuit Breaker en Actuator
management.health.circuitbreakers.enabled=true

logging.level.org.springframework.security=DEBUG
